# Generated by Django 4.1.1 on 2022-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_messgae_blog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
